### ISSUE TITLE
Latest tag stopped working

### ISSUE THREAD

**Issue by eivantsov** [openshift/ansible-service-broker#1042]
**What happened**:

When enabling ansible service broker in OKD 3.10, APBs never show up in the UI. Nothing suspicious in logs though.

It worked for me yesterday, but when I recreated the cluster, I was unable to find any APBs in web console.

I looked at https://hub.docker.com/r/automationbroker/automation-broker-apb/tags/ and saw that latest tag was updated.

After manually updating dc to be using nightly tags for this image, the problem's gone.

**Comment by djzager** [comment]
https://github.com/openshift/origin/pull/20583
https://github.com/openshift/origin/pull/20584

**Comment by djzager** [comment]
> After manually updating dc to be using nightly tags for this image, the problem's gone.

I'm not certain I understand you. You point to the `automation-broker-apb` tags and say, "updating dc to be using nightly tags for this image." There is no deploymentconfig that would have the automation-broker-apb, only pods.

My belief is that you are suggesting you updated the broker's deploymentconfig to use the nightly tag and the problems went away. This would likely be because the broker and broker-apb `latest` images are out of sync:

```
➜  ~ docker run --rm --entrypoint rpm docker.io/ansibleplaybookbundle/origin-ansible-service-broker:latest -qa | grep 'broker'
ansible-service-broker-1.3.5-1.20180723203110.el7.x86_64
ansible-service-broker-container-scripts-1.3.5-1.20180723203110.el7.noarch
ansible-service-broker-selinux-1.3.5-1.20180723203110.el7.noarch

➜  ~ docker run --rm --entrypoint rpm docker.io/automationbroker/automation-broker-apb:latest -qa | grep 'broker'
automation-broker-apb-role-1.3.8-1.20180810192501.el7.noarch

➜  ~ docker run --rm --entrypoint rpm docker.io/ansibleplaybookbundle/origin-ansible-service-broker:nightly -qa | grep 'broker'
ansible-service-broker-1.3.8-1.20180810193359.el7.x86_64
ansible-service-broker-container-scripts-1.3.8-1.20180810193359.el7.noarch
ansible-service-broker-selinux-1.3.8-1.20180810193359.el7.noarch
```

This is actually my fault. I need to release a new broker container image and I'll do that this morning.

**Comment by eivantsov** [comment]
@djzager I means openshift-automation-service-broker deployment, sorry.

Can you please update the thread once a new latest tag is pushed? 

thank you

**Comment by eivantsov** [comment]
I can see a new tag, but still same behavior with Origin 3.10.
