### ISSUE TITLE
Proposal: Block out any passwords outputed to the logs

### ISSUE THREAD

**Issue by rthallisey** [openshift/ansible-service-broker#181]
It would be nice to print the parameters from apbs to stdout. But, we can't do that unless we blockout passwords.

**Comment by eriknelson** [comment]
+1, was just going to log this issue WRT to @jmrodri's feedback. I'm not sure how we can know which parameters are sensitive from the broker since that's really the domain of an APB. Could make this configurable maybe to only output params in debug mode?

Just also of note, the extra-vars are available if you describe the apb pod.

**Comment by eriknelson** [comment]
#151 merged.

**Comment by eriknelson** [comment]
Gah, sorry. Thought this was tracking that PR. This should remain open.

**Comment by shawn-hurley** [comment]
## Proposal

I think that the easiest way to solve this is to push the logic of determining the security of a parameter to the client. I think this means adding to the APB Spec a parameter that is either ```password```  or ```secure```(I think this makes more sense in case it is an API key or another secret).  

#### ASB Changes

Add to the ParameterDescriptor a field.
When printing out Parameters, will need to match parameter name with the spec name and determine if it is secret or not. 

#### APB Spec Changes

Add an optional parameter described above, that will default to not private. 

Just a thought that will not have us trying to infer if a parameter should be private or not
