### ISSUE TITLE
Using k8s Subject Rules Review when available.

### ISSUE THREAD

**Issue by shawn-hurley** [openshift/ansible-service-broker#427]
We would like to be able to use kubernetes the same as openshift. Currently, because k8s api does not have the `SubjectRulesReview` resource we can not support the same behavior for checking the user. Because of this, k8s users must set `auto_escalate` to true. 

The PR that we are waiting on is:
kubernetes/kubernetes#31292

**Comment by rthallisey** [comment]
The upstream PR for this adds a function called ```SelfSubjectRulesReview```, which gets the rules of the current user.  This is going to be a challenge remove auto_escalate for kubernetes when we need find a way to get the rules of a user that we aren't identified as.

**Comment by rthallisey** [comment]
@shawn-hurley, let me know if I'm missing any details, but you mentioned that when we create the apb's service account, we will have its token.  So your idea was that maybe we can make a request with that token to pretend we are the apb user in order to get a ```SelfSubjectRulesReview``` from kubernetes.

Maybe we can pull in @enj into this discussion to see if this is a potential path forward.

**Comment by shawn-hurley** [comment]
@rthallisey I was wondering if there was any way to impersonate the originating user to get the self-subject rules review, I was wondering if there was some way to retrieve that users token.

**Comment by jmrodri** [comment]
Fixed by PR #995
