### ISSUE TITLE
Break up broker.go

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#499]
broker/broker.go is starting to become monolithic, pushing 1300 lines. I would suggest we start to break things up by method, i.e. {provision, bind, update}_handler.go etc.

**Comment by jmrodri** [comment]
It is a bit monolithic but that's because it is ALL `AnsibleBroker` methods. If this were a java project that's where they would all have to live since you wouldn't be able to break them apart. If we move things out by method we'll be going against what we mentioned about trying to keep the methods near the struct definitions. 

And would we break it up by ALL methods? i.e. provision, bind, validateDeprovision, LastOperation, etc? or are you suggesting only the main API methods i.e. provision, bind, update, unbind, deprovision, lastoperation? I *think* that's what the original copy of the broker looked like before we consolidated them.

I've got mixed feelings about breaking it apart. Right now I see 1072 lines in the file (from master). Out of that 1072 there are 205 lines of comments and 102 log statements.

Also the formatting of some of that code inflates the line count:

```
    if req.PlanID == "" {
        errMsg :=
            "PlanID from provision request is blank. " +
                "Provision requests must specify PlanIDs"
        return nil, errors.New(errMsg)
    }
```

The above is 6 lines, but if we went with the longer format, it goes down to 4. 

```
    if req.PlanID == "" {
        errMsg := "PlanID from provision request is blank. Provision requests must specify PlanIDs"
        return nil, errors.New(errMsg)
    }
```
And removing the variable declaration, I'm down to 3. 
```
    if req.PlanID == "" {
        return nil, errors.New("PlanID from provision request is blank. Provision requests must specify PlanIDs")
    }
```

So simply using a longer format I've cut some of the line count in half. Now I'm not saying we go for a longer line format, just trying to point out that I'm not sure it's that HUGE of a file that it needs breaking up.

On Candlepin, our longest file was 2498 lines long.

```
2498 ./server/src/main/java/org/candlepin/resource/ConsumerResource.java
2497 ./server/src/main/java/org/candlepin/controller/CandlepinPoolManager.java
2376 ./server/src/test/java/org/candlepin/service/impl/DefaultEntitlementCertServiceAdapterTest.java
2187 ./server/src/test/java/org/candlepin/model/PoolCuratorTest.java
2098 ./server/src/test/java/org/candlepin/policy/js/compliance/ComplianceRulesTest.java
1868 ./server/src/test/java/org/candlepin/controller/PoolManagerTest.java
1655 ./server/src/main/java/org/candlepin/model/PoolCurator.java
1577 ./server/src/main/java/org/candlepin/resource/OwnerResource.java
1569 ./server/src/test/java/org/candlepin/resource/OwnerResourceTest.java
1471 ./server/src/main/java/org/candlepin/model/Pool.java
```

Compare the above to the broker codebase:
``
1072 ./pkg/broker/broker.go
837 ./pkg/origin/copy/authorization/zz_generated.deepcopy.go
815 ./pkg/origin/copy/authorization/validation/validation_test.go
645 ./pkg/handler/handler.go
605 ./pkg/origin/copy/authorization/types.go
567 ./pkg/origin/copy/authorization/validation/validation.go
535 ./pkg/handler/handler_test.go
443 ./pkg/dao/dao.go
403 ./pkg/app/app.go
350 ./pkg/broker/util_test.go
```

And have you seen the k8s source tree? :)

```
73789 ./golang.org/x/text/collate/tables.go                
```

That's probably not fair since I think tables is generated. So I went looking for files that might not be generated. Removing generated, table, test and data, types would be even larger.

```
find . -name '*.go' -exec wc -l '{}' \; | grep -v generated | grep -v table | grep -v test | grep -v data | sort -nr | head 
24201 ./k8s.io/kubernetes/pkg/kubelet/apis/cri/v1alpha1/runtime/api.pb.go
16549 ./github.com/coreos/etcd/etcdserver/etcdserverpb/rpc.pb.go
6944 ./github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.go
5983 ./github.com/googleapis/gnostic/OpenAPIv3/OpenAPIv3.go
4617 ./k8s.io/kubernetes/staging/src/k8s.io/client-go/pkg/api/v1/types.go
4617 ./k8s.io/kubernetes/pkg/api/v1/types.go
4617 ./k8s.io/client-go/pkg/api/v1/types.go
4456 ./github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
4373 ./github.com/googleapis/gnostic/OpenAPIv3/OpenAPIv3.pb.go
4218 ./k8s.io/kubernetes/pkg/api/validation/validation.go
```

So to make a long story short, in the grand scheme of things, I don't think broker.go is long at all :) Even if it hit 2000 lines.

**Comment by rthallisey** [comment]
I'm in favor of evaluating this even if we only trim it down a couple of lines.  Either way, like Zeus said it's not that long.

**Comment by rthallisey** [comment]
@eriknelson What sparked the desire to create this issue besides that it's 1300 lines? Does it not read well?  Is it hard to find what you're looking for?  I want to further understand what you mean by 'monolithic'.

**Comment by eriknelson** [comment]
@rthallisey Monolithic is probably the wrong word to use, I'm mostly coming from a place where, one file is responsible for one concern, and if that file starts to get too large, it may be indicative of a code smell where a single component is becoming responsible for too many things. To be clear: my complaint isn't literally the line count; it's the fact that it might be a symptom of too much responsibility.

> And would we break it up by ALL methods? i.e. provision, bind, validateDeprovision, LastOperation, etc? or are you suggesting only the main API methods i.e. provision, bind, update, unbind, deprovision, lastoperation?

Certainly not one file per method. Breaking up by method and relevant utility functions makes sense to me. deprovision_handler.go contains core Deprovision + validations.

@jmrodri Fair point RE: the comments, I've often found myself wondering how much of them are even accurate anymore.

**Comment by jmrodri** [comment]
If it is too much responsibility I can certainly see that, there are some utility methods in there that could be moved out. And we could refactor some of the methods down to do a better job of consolidating.

**Comment by jmrodri** [comment]
I'm ok with possibly refactoring the AnsibleBroker to be more modular or separate the concerns better. What I don't want to do is break up a file purely because it is "too long" to satisfy some sort of line count. So +1 to looking into this.

**Comment by eriknelson** [comment]
> What I don't want to do is break up a file purely because it is "too long" to satisfy some sort of line count

Agreed, that's not a great reason in and of itself.

**Comment by eriknelson** [comment]
I'm going to close this. With the BrokerSDK on the horizon, I see this getting handled naturally.
