### ISSUE TITLE
Change default development template whitelist to `*`

### ISSUE THREAD

**Issue by dymurray** [openshift/ansible-service-broker#823]
For development we don't want to enforce a whitelist in the local registry adapter because new APB developers do not realize that they have to name their APB `$name-apb`. Let's change the default behavior to allow all naming conventions unless the user explicitly changes it since this template will be used for development.

**Comment by eriknelson** [comment]
We don't really have a development template, per se? It's really just the one deployment template. My gut reaction is I'm a little concerned with opening this up, but I understand the complaint. I also definitely do not want to add *more* specialized deployment templates that we have to support.

How are these folks usually bringing up their cluster and broker? `run_lastest_build.sh` and `minishift`? Can we add some logic that maybe patches the deployment instead of the default template value?

**Comment by shawn-hurley** [comment]
My initial reaction is that the deployment templates are all for development, and openshift-ansible is the way to install for prod use cases. 

I am not opposed to making the default white_list a parameter for the template, we could make this updatable. I say we keep the default to `"*"` though.

**Comment by eriknelson** [comment]
@shawn-hurley that sounds reasonable. As discussed in IRC, let's call out the fact that we're defaulting to open. Otherwise, LGTM.
