### ISSUE TITLE
./run_latest_build.sh on MAC OS X?

### ISSUE THREAD

**Issue by jonnyfiveiq** [openshift/ansible-service-broker#843]
Not sure if this is an issue or not...

oc cluster up is supported on MAC OS X,

but this script I think is not...

Here is the first line after the comments

DOCKER_IP="$(ip addr show docker0 2>/dev/null | grep -Po 'inet \K[\d.]+' 2>/dev/null)"

ip addr does not exist as a command in MAC OS X, and whilst grep does exist, the version MAC OS X has does not support the -Po flags...

So I cant see how this script would ever work on MAC? thanks

**Comment by rthallisey** [comment]
We've had may issues opened over this script on MAC and would love to get it working.  Feel free to post a pull request.

**Comment by jonnyfiveiq** [comment]
ok confirmed....its not for mac then. Before pull request on mac I would like to see it working on centos7 but am seeing issues there....will debug more. thanks

**Comment by djzager** [comment]
A pull request to have `./run_latest_build.sh` working for Mac would certainly be appreciated. In the case you are not aware we have a setup for [minishift](https://github.com/minishift/minishift-addons/tree/master/add-ons/ansible-service-broker) and minishift works on Mac.

**Comment by jwmatthews** [comment]
@jonnyfiveiq 

FYI @tsanders-rh and I often run on Mac and we use https://github.com/fusor/catasb/blob/master/local/mac/run_mac_local.sh

catasb is running oc cluster up and handling a few other edge cases.

**Comment by shawn-hurley** [comment]
Hi everyone,

I was just able to [validate](https://paste.fedoraproject.org/paste/kYiLj1H-U0GUY1vnpd2IHA) the run_latest_buld.sh works on mac if you just run the script
`./run_latest_build.sh`.

The only thing that I think could be an issue is: `sing Docker shared volumes for OpenShift volumes` could this be an issue @jwmatthews

**Comment by jwmatthews** [comment]
I've run ./run_latest_build.sh twice now on Mac with differing results.

First run, failure to bring up Service Catalog
$ time ./run_latest_build.sh 
Using Docker shared volumes for OpenShift volumes
Using 127.0.0.1 as the server IP
Starting OpenShift using docker.io/openshift/origin:latest ...
Skip persistent volume creation 
-- Starting OpenShift container ... 
   Creating initial OpenShift configuration
   Starting OpenShift using container 'origin'
   Waiting for API server to start listening
   OpenShift server started
-- Adding default OAuthClient redirect URIs ... OK
-- Installing registry ... 
   scc "privileged" added to: ["system:serviceaccount:default:registry"]
-- Installing router ... OK
-- Importing image streams ... OK
-- Importing templates ... OK
-- Importing internal templates ... OK
-- Installing service catalog ... OK
-- Installing template service broker ... OK
-- Registering template service broker with service catalog ... FAIL
   Error: cannot register the template service broker
   Caused By:
     Error: cannot create objects from template openshift-infra/template-service-broker-registration
     Caused By:
       Error: unable to recognize servicecatalog.k8s.io/v1beta1, Kind=ClusterServiceBroker: no matches for servicecatalog.k8s.io/, Kind=ClusterServiceBroker

I then restarted the Docker VM on Mac.
    Clicked on the Docker preferences and selected "restart".

Retried run_latest_build.sh and success with oc cluster up and service catalog coming up.
Yet our broker failed to come up, still debugging what went wrong there.

Note that on Mac I routinely see the first error I noted, it seems like sometime during ~3.9 development cycle a change was introduced, I guess to 'oc'.  I would see many runs fail of oc cluster up, with an occasional success...yet if I restart the docker VM I see success...haven't debugged further to find the root cause, unsure if this is just on my setup with an older docker version or a more widespread issue.

I am still using Docker version 1.12.6 (14937)
