### ISSUE TITLE
Consider authenticating the dashboard redirector

### ISSUE THREAD

**Issue by eriknelson** [openshift/ansible-service-broker#901]
The dashboard redirector alpha feature is unauthenticated. What are the implications of returning the `dashboard_url` to anyone with the correct service instance ID and access to the the redirector?

**Comment by mhrivnak** [comment]
I raised this question because the owner for a service that has its own authn and authz could reasonably think it's appropriate that, when handing a dashboard URL directly to the thing that just provisioned it, it's ok to include an auth token of some kind that implicitly authorizes access. In such a case where simple possession of the URL gives you access to the dashboard, the service ID would become the key for obtaining that access from the redirector.
